### ISSUE TITLE
add support for checkbox problems

### ISSUE THREAD

**Issue by pdpinch** [mitodl/rapid-response-xblock#76]
As an instructor I'd like to be able to apply the Rapid Response aside to checkbox problems, in addition to multiple choice problems. 

### acceptance criteria
- [x] In Studio, course authors should be able to enable Rapid Response on checkbox problems the same as mutiple choice problems. 
- [x] in LMS, the rapid response aside for opening and closing the problem, and for seeing the graphed results should be visible for instructors on checkbox problems.  
  - [x] The graph should display a histogram of responses for each checkbox answer. For example if there is one student response, and the student selected choice 1 and choice 3, then the graph should show a bar of magnitude 1 for choice 1 and for choice 3. 
- [ ] in LMS, the aside xBlock should filter and parse checkbox events, recording any events for a checkbox problem that is open
- [ ] The downloadable instructor report should have a row per student event. The "submitted answer" field should contain a concatenation of the student's choices. For now, any convenient concatenation is fine -- it could even be JSON.

**Comment by tasawernawaz** [comment]
@pdpinch I have opened a PR (WIP) #77 for this issue. I am able to add support for checkbox problems in studio. However I am facing error in JS while viewing in LMS. 

![screen shot 2018-12-11 at 6 09 04 pm](https://user-images.githubusercontent.com/4245618/49802858-06613b00-fd70-11e8-84a5-5da89ec2a81f.png)

Can I get some understanding that how we are building charts for multiple choice problems that  would be much helpful to render chart for checkbox problem.

**Comment by pdpinch** [comment]
@gsidebo or @noisecapella should be able to help.

I don't know if you pushed all your code so far, but at the very least, I expect that you'll need to look at 1) how we are parsing the student events and 2) how the API aggregates them for the lms frontend.

**Comment by tasawernawaz** [comment]
@pdpinch I have pushed code at https://github.com/mitodl/rapid-response-xblock/pull/77.

**Comment by tasawernawaz** [comment]
@pdpinch I am able to fix the above issue. This is how we are saving submissions for checkbox problems.

```
mysql> select answer_id, answer_text, run_id, user_id from rapid_response_xblock_rapidresponsesubmission;
+-----------------------------------------+---------------------------------------------------+--------+---------+
| answer_id                               | answer_text                                       | run_id | user_id |
+-----------------------------------------+---------------------------------------------------+--------+---------+
| [u'choice_0', u'choice_1', u'choice_2'] | [u'option a - correct', u'option b', u'option c'] |      8 |       7 |
| [u'choice_3']                           | [u'option d - correct']                           |      8 |       6 |
+-----------------------------------------+---------------------------------------------------+--------+---------+
```

@gsidebo May be you can point me to the code where we are parsing this data to load histogram.

**Comment by tasawernawaz** [comment]
@pdpinch @gsidebo 

This is how histogram looks like, all options are treated separately, 
![screen shot 2018-12-12 at 7 24 49 pm](https://user-images.githubusercontent.com/4245618/49877255-d46ed800-fe46-11e8-8294-dc79de55f595.png)

This is how CSV looks like 
[rapid_response_submissions for checkbox problem.zip](https://github.com/mitodl/rapid-response-xblock/files/2672281/rapid_response_submissions.for.checkbox.problem.zip)

**Comment by gsidebo** [comment]
@tasawernawaz A few things:
1. The number of overall responses per run (the number you see in the select box) is not correct for checkbox problems. If one user selects 4 checkboxes and submits, that counts as 1 response, not 4
1. I am most definitely not comfortable with the idea of saving the value of the answer ids and answer text exactly as they exist in the event data, then using `eval` to create a Python list of id's when we build the data for a checkboxes responses histogram. `eval` is strongly discouraged as a general programming practice, but we will also have some specific reasons to avoid it. For example, if some breaking change was made to the structure of the event data on the edX side, we would to know about that at the time of parsing the submissions rather than at the time of gathering the responses data. We would not want a bunch of saved `RapidResponseSubmission` objects that we couldn't handle in our application logic. We would want to guarantee that our application logic can work with all of those objects. We _could_ add a new model that represents each individual answer for a single submission, but we could still get away with representing the multiple checkbox answers as a string. Instead of a direct string representation of the Python list, we should save the list as a JSON string (via `json.dumps`)
1. Instead of creating a bunch of boolean forks to handle the difference in logic between multiple choice and checkbox responses, we should create classes that implement the same methods and a simple factory method to return an object of the correct class. The logical differences between the 2 problem types come into play in these scenarios: [1] Parsing problem answer ids and answer text from the event data, [2] given a problem object, parse choices from problem XML and return a list of dicts representing those choices, [3] given a problem object, build the problem response count dict ({choice_id: {run_id: # specific answers for that choice id during this run}, ...}). The classes should implement methods for all 3 of those. We would need to be able to get an object of the correct class with event data or a problem object (`modulestore().get_item(self.wrapped_block_usage_key)`). That's what the factory method(s) would be for.

Let me know if you have any questions

**Comment by tasawernawaz** [comment]
@gsidebo Thank you for such a detailed feedback. 

@pdpinch Your feedback would also be helpful before moving forward and refactoring. I believe this require enough work which is not do able before weekend. Right now, I am not sure, who is going to take over this from me?

**Comment by pdpinch** [comment]
1. Gavin is correct. The number of response should be the same as the number of student events. 
2. I agree that using `eval` is a bad idea. I do prefer one record per student response, using a string to combine the multiple checkbox answers. 
3. I know this is more work, but I think it will build a better foundation for other problem types in the future. 

Regarding the timing, Ferdi's let me know that we don't need to include this in the 12/24 release. Please spend another day on it and then let's check in to decide how best to proceed. It could wait for you to return.

**Comment by tasawernawaz** [comment]
@pdpinch Thank you! that news released some pressure from me. :)

I guess no.1 and 2 should be done after restructuring code (no.3), so it makes sense to build foundation before fixing 1 and 2.

**Comment by tasawernawaz** [comment]
@pdpinch While taking a look back at this issue, I saw another issue is opened https://github.com/mitodl/rapid-response-xblock/issues/79 to refactor the code of our last couple of PRs. What do you think should we continue with this change or should we refactor our existing code before adding new.

**Comment by pdpinch** [comment]
It would be best to get this feature released by the end of the month. 

The refactoring won’t become an issue until we upgrade to Ironwood, in April or May.

**Comment by pdpinch** [comment]
We never actually needed this
