### ISSUE TITLE
Migrate Travis -> Github Actions

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/rapid-response-xblock#82]
Travis will be limited open source projects build time soon, so we need to transition to github actions. 

Take a look at how we did it [open discussions](https://github.com/mitodl/open-discussions/pull/3204) or [bootcamps](https://github.com/mitodl/bootcamp-ecommerce/pull/1086) or [micromasters](https://github.com/mitodl/micromasters/pull/4682)

**Comment by arslanashraf7** [comment]
@pdpinch While working on this ticket I see that some tests are breaking in Travis as well as GitHub actions (Associated PR).

Failing tests indicate that there has been a major refactoring in `edx-platform` for `CapaModule` which has affected our `rapid-response-xblock`. Since fixing the aforementioned goes way beyond the scope of this specific ticket so I've added a new issue for you to have a look at. You can see the issue here https://github.com/mitodl/rapid-response-xblock/issues/85
