### ISSUE TITLE
Studio view for instructor to identify which problems will get rapid response

### ISSUE THREAD

**Issue by pdpinch** [mitodl/rapid-response-xblock#9]
As a course author, I need to be able to indicate which Units/XBlocks will gather learner responses and display the rapid response graph. 

### out of scope
- improving the Aside UX for aside settings

**Comment by gsidebo** [comment]
It occurred to me that the only implemented aside does not actually have a studio view, so the existing code for rendering the aside studio views in `edx-platform` is unused, and it wouldn't surprise me if there wasn't a lot of though put into the placement of that rendered fragment. I think it's likely that edX will be OK with us moving the aside studio view rendering (I don't think it makes any sense where it is now). I'll talk to Dave about this

**Comment by gsidebo** [comment]
Here are some screenshots which illustrate why I think the studio rendering makes no sense as-is:

![ss 2018-02-27 at 12 59 35](https://user-images.githubusercontent.com/14932219/36745668-435d2684-1bbe-11e8-8cc2-bf4e554806e8.png)

![ss 2018-02-27 at 13 00 11](https://user-images.githubusercontent.com/14932219/36745669-4375f3ee-1bbe-11e8-9e04-1ad84fcac2fa.png)

**Comment by gsidebo** [comment]
@Ferdi - I was told by @pdpinch that you were wondering about the value/necessity of this issue.  Here's my take:

What we're doing in this issue is letting instructors explicitly say which problems they want to enable for rapid response. If we don't provide this capability to instructors, there are our options:

1. Limit the blocks that we consider for rapid response in some other way, such as Django settings. This has a few drawbacks. Among them: we would need to own that configuration, and the courses would not export in a way that keeps the rapid response setting.
1. Simply consider every multiple choice problem as a rapid-response problem. In that case, every single multiple choice problem (and any other problem types we intend to support) will appear to the instructor like the screenshot below, even if the problem is not intended for an in-class experience (homework, quizzes, etc.). It would also show for instructors that have no familiarity or need for the rapid response functionality at all. This would be jarring to instructors trying to compose their courses.

![ss 2018-03-15 at 10 54 08](https://user-images.githubusercontent.com/14932219/37481217-9705acac-2857-11e8-8e1e-5fc8e769a132.png)
